### ISSUE TITLE
language-selector.js:89 Uncaught TypeError: $(...).adddropdown is not a function

### ISSUE THREAD

**Issue by steeve-san** [clemdesign/grav-plugin-language-selector#10]
Hi, 

I have a small problem with your plugins : 

language-selector.js:89 Uncaught TypeError: $(...).adddropdown is not a function
    at HTMLButtonElement.<anonymous> (language-selector.js:89)
    at Function.each (jquery-2.x.min.js:2)
    at n.fn.init.each (jquery-2.x.min.js:2)
    at HTMLDocument.<anonymous> (language-selector.js:88)
    at i (jquery-2.x.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.x.min.js:2)
    at Function.ready (jquery-2.x.min.js:2)
    at HTMLDocument.J (jquery-2.x.min.js:2)

Regard

**Comment by clemdesign** [comment]
Hi, did you add jQuery to your [Grav theme](https://learn.getgrav.org/16/themes/asset-manager#example) or [Grav configuration](https://learn.getgrav.org/16/themes/asset-manager#configuration) ?

**Comment by steeve-san** [comment]
Hi, Yes JQyery is add on grav Configuration "
Collections
 jquery
   system://assets/jquery/jquery-2.x.min.js
 script
  https://www.google.com/recaptcha/api.js
  https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js

**Comment by clemdesign** [comment]
This plugin it is correctly loaded by your page? (Ctrl + U and check that link to jQuery is right)

Did you use another javascript plugin that use the anchor $()?

**Comment by steeve-san** [comment]
Hi Clem, 

Yes My plugins is loaded and my JS 
"<script src="/system/assets/jquery/jquery-2.x.min.js"></script>
<script src="/user/plugins/language-selector/js/language-selector.js"></script>"

"<div class="g-block size-10">
             <div id="language-selector-8550-particle" class="g-content g-particle">            <div class="language-selector">
  <button class="btn" type="button" data-dropdown="langSelectorList">
        <img alt="Français" src="/user/plugins/language-selector/flags/fr.png" />
            <i class="fa fa-caret-down"></i>
  </button>

  <ul class="dropdown-menu" id="langSelectorList">

                    
            <li>
  </ul>
</div>"

My I don't use js, maybe my theme probably " Gantry_5 Helium".

Regard

**Comment by clemdesign** [comment]
Ok. Why do you use a version 2.x? What is the exact version of your jQuery?

**Comment by steeve-san** [comment]
/*! jQuery v2.2.4 | (c) jQuery Foundation | jquery.org/license */

**Comment by clemdesign** [comment]
Maybe try to use this code integration:
```
<script
  src="https://code.jquery.com/jquery-2.2.4.min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script>
```
Ensure that your jQuery is loaded first.
