### ISSUE TITLE
Selector not working - selection menu will not show up

### ISSUE THREAD

**Issue by hemmond** [clemdesign/grav-plugin-language-selector#13]
Hi. I've noticed that the selector no longer seems to work. It is set to one language (the one retrieved from environment in my case). 

Current behavior: 
When clicked on the selector, nothing happens. 

Expected behavior: 
When clicked on the selector, the roll-down menu with supported languages should appear. 

Versions: 
I am using Grav v1.7.42.3; Language Selector v1.1.0. 

Tested on: 
Firefox 115.0.2 (64 bit, windows 10)
Firefox 115.2.1 (Build #2015962859, Android 11)
Chrome 114.0.5735.196 (Android 11)
Edge 114.0.1823.82 (64 bit, Windows 10)

It worked on about 2 years old Firefox version, don't know which version. If requested I can retrieve the version in a few days.

**Comment by dspaan** [comment]
The button is gone on our page too. I pretty sure it worked before:
https://handleiding.telforce.nl/nl

Any idea?

**Comment by clemdesign** [comment]
I upgraded to last Grav version (1.7.44) and no issue detected about this plugin.

I think maybe a breaking configuration or maybe another plugin which interfere with this one.

Let me know about your investigation.

**Comment by clemdesign** [comment]
I close this issue
