### ISSUE TITLE
does code for chinese traditional language exist ?

### ISSUE THREAD

**Issue by shamantao** [clemdesign/grav-plugin-language-selector#14]
Hi,
I try to find the code to have traditional chinese in my choices of languages. But I can not find correct one.
I tried 
- ch
- zh
- cht
- zh-ch
- zh-cht
- cmn

nothing works correctly for me. I mean by that some are simplified chinese and not traditional. zh-cht for example. cmn show just cmn and not Mandarin

Do you know where i can find the correct code please ? 

ps: I don't need the flag as i see on [the article](https://www.unitedlanguagegroup.com/blog/inside-design-a-language-selector-is-no-place-for-flags#:~:text=By%20choosing%20the%20flag%20of,portion%20of%20their%20target%20audience.&text=On%20the%20other%20side%20of,to%20a%20lone%20official%20language)

**Comment by clemdesign** [comment]
Hi,

I'm not familiar with these languages so I can't to determine subtleties between versions.

This plugin is just an language selection and use data from libraries or CMS core.

The name of languages is provided from https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Language/LanguageCodes.php

The flag used in selector shall be provided in this plugin at https://github.com/clemdesign/grav-plugin-language-selector/tree/master/flags

Hope this helps

**Comment by shamantao** [comment]
Yes Thanks!
 I found the right code : zh-TW in the php above. That waht I miss.
It works perfectly now.
No need flag
Thank You
