### ISSUE TITLE
Language switching is not always using the right slug

### ISSUE THREAD

**Issue by parijke** [clemdesign/grav-plugin-language-selector#3]
I have a page with subpages. The main page got a translated slug. Folder name is services and slug name (for NL) is 'diensten'

When I select that item when in the language NL it says /nl/diensten (which is fine)

When I am in English it says /en/services (which is fine too)

But when the item is the active item, and I switch from English to NL (Dutch) is says /nl/services (which is not fine). As I click the menu-item again, it says the url = /nl/diensten again (which is fine)

I don't know if this is a languageswitcher problem or a native Grav problem

**Comment by parijke** [comment]
It is not a plugin issue I think

**Comment by hh-ReBOOM** [comment]
No, it is a grav issue. Once a request is handled everything is frozen so you cannot retrieve anything 'outside' the active language. Therefore I created a plugin to cache the language specific slugged URLs. See [here on github](https://github.com/getgrav/grav-plugin-langswitcher/issues/39#issuecomment-503979879).
