### ISSUE TITLE
Simple Search problem!

### ISSUE THREAD

**Issue by LokyStaz** [clemdesign/grav-plugin-language-selector#4]
Hi. I got the same issue describe there : https://github.com/getgrav/grav-plugin-simplesearch/issues/58
How would be the way to use the workaround with this plugin ?!
Thank

**Comment by clemdesign** [comment]
Hi, in fact, Language Selector is not enabled in search page for me. So this issue is not visible.
But maybe you can resolve it by replacing `uri.params` by `uri.url(false)` in `user/plugins/language-selector/templates/partials/language-selector.html.twig` ?

**Comment by clemdesign** [comment]
Without answer, i consider closed. Please add new issue if it is not the case.
