### ISSUE TITLE
Multi Site and Multi Language

### ISSUE THREAD

**Issue by AndrewNB** [clemdesign/grav-plugin-language-selector#5]
Hi,

I am having issues with this plugin going to the correct link.  

I have a grav site setup with multi-site.  The subsites are what I am translating into multiple languages so it ends up like this:

Main site:
www.site.com
Subsite:
www.site.com/sub-site
Subsite Page(english): 
www.site.com/sub-site/my-page
Subsite Page(french): 
www.site.com/sub-site/my-page/fr

The translations work great.  But when I use the plugin to switch language it directs me back to the parent site.  So for example if I am viewing www.site.com/sub-site/my-page/fr and choose to change to English I get directed to:  www.site.com/my-page/fr.  Any tips on how I can get around this to make sure it gets the subsite included in the link it creates?  

I tried editing the plugin template however I ended up with both languages directing to (fr).  

Cheers,

**Comment by clemdesign** [comment]
Hi Andrew,

So, translated URI is based on [rawRoute()](https://learn.getgrav.org/content/multi-language#language-alias-routes) in the [php file](https://github.com/clemdesign/grav-plugin-language-selector/blob/0793b8c48c945f96650fdc8c7b5ad7c0a93ca271/language-selector.php#L64).
I do not have multisite so I can't test which variable takes the "sub-site" information but I think you can build a new URL that includes "sub-site" with one of these [URI objects](https://learn.getgrav.org/themes/theme-vars#uri-object) or [Core Objects](https://learn.getgrav.org/themes/theme-vars#core-objects).

Keep us informed if you find a solution.

Cheers
