### ISSUE TITLE
TRUE OR FALSE : be aware ??

### ISSUE THREAD

**Issue by JOduMonT** [clemdesign/grav-plugin-language-selector#6]
must have define language before activating the plugins unless you will get eoor

![image](https://user-images.githubusercontent.com/5204724/47057690-11f61280-d1c2-11e8-969b-372023a79dec.png)

**Comment by clemdesign** [comment]
Hi,
I added a note in README.md about this required configuration.
I close this issue but robustness in code will be treated in the next version.
