### ISSUE TITLE
Plugin name TWIG variable syntax problem

### ISSUE THREAD

**Issue by trianity** [clemdesign/grav-plugin-language-selector#8]
Hello, 
First of all thank you very much for the developing this plugin.

In the real word use there is a problem with plugin name.
If you use the plugin name "language-selector" the PHP part of the plugin will work well, but the TWIG use of the plugin config variable will fail.

For example:
```
{% if config.plugins.language-selector.enabled %}
  {% include 'partials/language-selector.html.twig' %}
{% endif %}
```
This TWIG code will never include the plugin template because there is a syntax error in the TWIG array selector.

Only the 'config.plugins.languageselector.enabled' or the 'config.plugins.language_selector.enabled' variant will work from the TWIG side.

I have just tested it, and I had to rewrite the plugin without - in the plugin name to work properly with TWIG variables.

So, I suggest to change the name of this genius plugin for multi language GRAV sites.

**Comment by clemdesign** [comment]
Hello,

I'm glad you like this plugin.

For this kind of plugin, you can simply use :

```
{% if config.plugins['language-selector'].enabled %}
  {% include 'partials/language-selector.html.twig' %}
{% endif %}
```

In this way, you can adress all fields of the plugin.
