### ISSUE TITLE
Grav Language selector and slug

### ISSUE THREAD

**Issue by frankrko** [clemdesign/grav-plugin-language-selector#9]
I tried to set up a website with 2 languages using Grav/Gantry backend. One NL (default) and one EN. Only the EN page use slug. When opening pages using EN, I can see all the webpages with the right slug name as URL. I can easily switch to the NL pages. When trying to go back from NL to EN, it will not find the page as it will go to the naming of the page instead of the slug variant. Example:
Folder Name: matlessen
NL menu: Matlessen
EN menu: Mat Classes
EN Slug: matclass

When going from EN to NL, the url will go from ../en/matclass to ../nl/matlessen
When trying to move from NL to EN, the url try to find ../en/matlessen instead of the slug ../en/matclass 

Is this an plugin issue ?
Thanks in advanced
Frank

**Comment by clemdesign** [comment]
According to this [issue](https://github.com/clemdesign/grav-plugin-language-selector/issues/3), it seem not a plugin issue.

Can you confirm that is the same behavior?

**Comment by frankrko** [comment]
I maybe should have looked at the closed issues before. Yes, it is more less the same behavior. A pity that this is a Grav issue not dealing rightly with language switching. Means I will look for another CMS platform.

**Comment by hh-ReBOOM** [comment]
I posted a possible solution [here on github](https://github.com/getgrav/grav-plugin-langswitcher/issues/39#issuecomment-503979879).

**Comment by clemdesign** [comment]
Hi hh-ReBOOM,

Could you open an [issue](https://github.com/clemdesign/grav-plugin-language-selector/issues/new) to describe your solution and discuss about it please?

It will also help people to find a solution to this issue while waiting for the correction.

Thanks.
